# Generated by Django 3.2.3 on 2021-05-31 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hizlaria',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('abizenak', models.CharField(max_length=100, unique=True)),
                ('alderdia', models.CharField(choices=[('ARARTEKO', 'Arartekoa'), ('EAJ', 'EAJ'), ('EB', 'Ezker Batua'), ('EH Bildu', 'Bildu'), ('EP', 'Elkarrekin Podemos'), ('N', 'Ezezaguna'), ('PP', 'PP'), ('PSE-EE', 'PSE'), ('UPyD', 'UPyD')], max_length=100)),
                ('generoa', models.CharField(choices=[('E', 'Emakume'), ('G', 'Gizon'), ('N', 'Ezezagun')], max_length=100)),
                ('informazioa', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Hizlariak',
            },
        ),
        migrations.CreateModel(
            name='ParteHartzea',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='parte-hartzearen data')),
                ('p_ordena', models.IntegerField(default=0)),
                ('hizlaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bis.hizlaria')),
            ],
            options={
                'verbose_name_plural': 'ParteHartzeak',
                'unique_together': {('data', 'p_ordena')},
            },
        ),
        migrations.CreateModel(
            name='Testua',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_ordena', models.IntegerField(default=0)),
                ('testua', models.TextField()),
                ('hizkuntza', models.CharField(max_length=10)),
                ('entitateak', models.TextField()),
                ('parteHartzea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bis.partehartzea')),
            ],
            options={
                'verbose_name_plural': 'Testuak',
                'unique_together': {('parteHartzea', 't_ordena')},
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
